#include "../include/version.h"

// Version history and changelog definition
const char* VERSION_CHANGELOG = 
  "Version 0.1.4 - WiFi Connection Failure Handling\n"
  "- Added STATE_WIFI_CONNECT_FAILED for connection failure handling\n"
  "- Implemented displayWiFiConnectionFailed() with error screen\n"
  "- Added 2-second failure display with automatic retry\n"
  "- Connection failures now show troubleshooting tips\n"
  "- Added red X pattern on NeoMatrix for visual error feedback\n"
  "- Automatic return to WiFi scan after connection failure\n"
  "- Updated both password entry and open network failure paths\n"
  "- Improved user experience with clear error messaging\n"
  "\n"
  "Version 0.1.3 - WiFi Password Entry System\n"
  "- Replaced 'prev' with 'select' functionality in WiFi results\n"
  "- Added complete character-by-character password entry system\n"
  "- Implemented STATE_PASSWORD_ENTRY with full character set support\n"
  "- Added automatic open network detection (skips password entry)\n"
  "- Created displayPasswordEntry() function with visual feedback\n"
  "- Added WiFi connection functionality with timeout handling\n"
  "- Updated button mappings: A=Next, B=Select, C=Rescan\n"
  "- Password entry: A=Cycle Char, B=Confirm Char, C=Submit\n"
  "- Added password masking and current character display\n"
  "- Improved user experience with proper state transitions\n"
  "\n"
  "Version 0.0.3 - Display Manager Refactoring\n"
  "- Added dedicated display clearing functions for better readability\n"
  "- Implemented clearTFTScreen() with optional color parameter\n"
  "- Added clearNeoMatrix() function for LED matrix clearing\n"
  "- Created clearAllDisplays() convenience function\n"
  "- Refactored all display functions to use new clear functions\n"
  "- Improved code maintainability and consistency\n"
  "\n"
  "Version 0.0.2 - Display & WiFi Improvements\n"
  "- Fixed display clearing issue between state transitions\n"
  "- Added complete WiFi networks display screen\n"
  "- Implemented displayCurrentNetwork() function\n"
  "- Added signal strength bars visualization\n"
  "- Color-coded security types (Open/WEP/WPA/WPA2)\n"
  "- Network navigation with button controls\n"
  "- Proper screen clearing in all display functions\n"
  "\n"
  "Version 0.0.1 - Initial Release\n"
  "- Added startup logo display with version number\n"
  "- WiFi network scanning functionality\n"
  "- Basic state machine architecture\n"
  "- TFT display support (240x135 ST7789)\n"
  "- Button handling system\n"
  "- Modular code structure\n";
